### ISSUE TITLE
Failing to parse date on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by keithpitt** [spotify/docker-gc#30] opened 2015-07-29 16:20 UTC
When I run `docker-gc` on Ubuntu 14.04.2 LTS, I get the following error message:

```
date: invalid date ‘"2015-07-29 16:16:2’
/usr/sbin/docker-gc: line 69: 1438186643 - : syntax error: operand expected (error token is "- ")
```

Am I doing something wrong? Thanks!

**Comment by mbruggmann** [comment] 2015-07-29 19:35
This is likely caused by the same issue as https://github.com/spotify/docker-gc/issues/29.

**Comment by rohansingh** [comment] 2015-09-28 16:53
Should be fixed like #29.

**Closed by rohansingh** 2015-09-28 16:53 UTC
